-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  updated_at timestamp with time zone
);
-- Set up Row Level Security (RLS)
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);
create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for todos
create table todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  text text not null,
  completed boolean default false,
  priority text check (priority in ('high', 'medium', 'low')) default 'medium',
  category text check (category in ('work', 'personal', 'shopping', 'health', 'other')) default 'other',
  due_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table todos enable row level security;

create policy "Individuals can create todos." on todos
  for insert with check (auth.uid() = user_id);

create policy "Individuals can view their own todos." on todos
  for select using (auth.uid() = user_id);

create policy "Individuals can update their own todos." on todos
  for update using (auth.uid() = user_id);

create policy "Individuals can delete their own todos." on todos
  for delete using (auth.uid() = user_id);
